import type { Metadata } from 'next';
import {  Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/shared/util/QueryProvider';
import AppHeader from '@/features/auth/components/app-header';


const geist = Geist({
  variable: '--font-geist',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Wheelhouse',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
  ${geist.variable}
  ${geistMono.variable}
    
         antialiased
         font-geist
         min-h-dvh
         flex
          flex-col
          w-full
         `}
      >
        <QueryProvider>
          <AppHeader />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
