import type { Metadata } from 'next';
import { Manrope, Unica_One } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/shared/util/QueryProvider';
import AppHeader from '@/features/auth/components/app-header';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const unicaOne = Unica_One({
  variable: '--font-unica',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Wheelhouse',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable}
  ${unicaOne.variable} 
         antialiased
         font-body
         min-h-dvh
         flex
          flex-col
          w-full
         `}
      >
        <QueryProvider>
          <AppHeader />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
